-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"
local terminal = "kitty"
local fileManager = "thunar"

-- Binds
hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- Add this line to handle Rofi's application launcher mode (drun)
hl.bind("SUPER + D", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("firefox"))

-- If waybar is running, kill it; if it's not, start it with explicit configs
hl.bind("SUPER + B", hl.dsp.exec_cmd("pkill waybar || waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css"))

hl.bind("SUPER + SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("bash -c wlogout"))
hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

-- Workspace switching
hl.bind("SUPER" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER" .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER" .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER" .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Window focus direction
hl.bind("SUPER" .. " + " .. "h", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER" .. " + " .. "l", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER" .. " + " .. "k", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER" .. " + " .. "j", hl.dsp.focus({ direction = "down" }))
-- Window Switcher / Cycling
hl.bind("ALT" .. " + " .. "Tab", hl.dsp.exec_cmd("snappy-switcher next"))
hl.bind("ALT + SHIFT" .. " + " .. "Tab", hl.dsp.exec_cmd("snappy-switcher prev"))
hl.bind("ALT + SHIFT" .. " + " .. "Tab", hl.dsp.window.cycle_next({ next = false }))

-- Mouse Binds
hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move window to workspace
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))

-- Media Keys / Testing
hl.bind("F6", hl.dsp.exec_cmd("notify-send HYPR TEST"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +10%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"))

-- Toggle your monochrome todo widget with Super + N
hl.bind("SUPER + n", hl.dsp.exec_cmd([[ /home/nrhnck/.config/conky/start-desktop.sh ]]))

-- Monitor Config
hl.monitor({
    output   = "eDP-1",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- Cursor
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", 20)


-- Screenshots
hl.bind(
    "Print",
    hl.dsp.exec_cmd([[bash -c 'mkdir -p ~/Pictures/Screenshots && FILE=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim -g "$(slurp)" "$FILE" && wl-copy < "$FILE" && notify-send "Screenshot Saved" "$FILE"' ]])
)

hl.bind(
    "SUPER + Print",
    hl.dsp.exec_cmd([[bash -c 'mkdir -p ~/Pictures/Screenshots && FILE=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim "$FILE" && wl-copy < "$FILE" && notify-send "Screenshot Saved" "$FILE"' ]])
)


-- Core Hyprland Configuration Block
hl.config({
     general = {
         gaps_in = 4,
         gaps_out = 4,
         gaps_workspaces = 0,
         border_size = 0,
         resize_on_border = false,
         allow_tearing = false,
         layout = "dwindle",
     },

     groups = {
         col = {
             active_border = { colors = { "rgba(d65d0eff)", "rgba(fe8019ee)" } },
         }
     },

     decoration = {
         rounding = 0,
         rounding_power = 0,
         active_opacity = 1.0,
         inactive_opacity = 1.0,

         shadow = {
             enabled = true,
             range = 10,
             render_power = 3,
             color = 0xee121212,
         },

         blur = {
             enabled = true,
             size = 7,
             passes = 1,
             vibrancy = 0.1696,
             ignore_opacity = true,
         },
     },

     misc = {
         force_default_wallpaper = -1,
         disable_hyprland_logo = false,
         vrr = 0,
     },
})

hl.curve("instant_snap", {
    type = "bezier",
    points = { {0.1, 1.0}, {0.1, 1.0} }
})

hl.animation({ leaf = "windows", enabled = true, speed = 1, bezier = "instant_snap", style = "popin 95%" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 2, bezier = "instant_snap", style = "slide" })
hl.animation({ leaf = "fade", enabled = true, speed = 1, bezier = "instant_snap" })
hl.animation({ leaf = "layers", enabled = true, speed = 1, bezier = "instant_snap", style = "fade" })

hl.window_rule({
    name = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({ match = { title = "Picture-in-Picture" }, float = true, size = { 640, 360 } })
hl.window_rule({ match = { class = "chrome-calendar.google.com__-Default" }, float = true, size = { 1280, 720 } })

-- Layer Rules (Waybar, SwayNC, logout)
hl.layer_rule({ match = { namespace = "gtk-layer-shell" }, blur = true })
hl.layer_rule({ match = { namespace = "waybar" }, blur = false })
hl.layer_rule({ match = { namespace = "match:namespace notifications" }, blur = true })
hl.layer_rule({ match = { namespace = "match:namespace swaync-notification-window" }, blur = false })
hl.layer_rule({ match = { namespace = "match:namespace swaync-control-center" }, blur = false })
hl.layer_rule({ match = { namespace = "match:namespace logout_dialog" }, blur = true })

hl.on("hyprland.start", function()
     hl.exec_cmd("waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css")
     hl.exec_cmd("hypridle")
     hl.exec_cmd("snappy-switcher --daemon")
     hl.exec_cmd("waypaper --restore")
     hl.exec_cmd("swaync")
     hl.exec_cmd("xsettingsd")
     hl.exec_cmd("/home/nrhnck/.config/conky/start-desktop.sh --auto")
end)
