-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"
local terminal = "kitty"
local fileManager = "thunar"

-- Binds
hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- Add this line to handle Rofi's application launcher mode (drun)
hl.bind("SUPER + D", hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("thunar"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("firefox"))

-- If waybar is running, kill it; if it's not, start it with explicit configs
hl.bind("SUPER + B", hl.dsp.exec_cmd("pkill waybar || waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css"))

hl.bind("SUPER + SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("bash -c wlogout"))
hl.bind("SUPER" .. " + " .. "F", hl.dsp.window.fullscreen())

-- Workspace switching
hl.bind("SUPER" .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER" .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER" .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER" .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER" .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER" .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER" .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER" .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER" .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER" .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Window focus direction
hl.bind("SUPER" .. " + " .. "h", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER" .. " + " .. "l", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER" .. " + " .. "k", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER" .. " + " .. "j", hl.dsp.focus({ direction = "down" }))
-- Window Switcher / Cycling
hl.bind("ALT" .. " + " .. "Tab", hl.dsp.exec_cmd("snappy-switcher next"))
hl.bind("ALT + SHIFT" .. " + " .. "Tab", hl.dsp.exec_cmd("snappy-switcher prev"))
hl.bind("ALT + SHIFT" .. " + " .. "Tab", hl.dsp.window.cycle_next({ next = false }))

-- Mouse Binds
hl.bind("SUPER" .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Move window to workspace
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = "1" }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = "2" }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = "3" }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = "4" }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = "5" }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = "6" }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = "7" }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = "8" }))
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = "9" }))
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }))

-- Media Keys / Testing
hl.bind("F6", hl.dsp.exec_cmd("notify-send HYPR TEST"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +10%"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"))

-- Super + A to quickly open your actual todo.org file for editing
hl.bind("SUPER + A", hl.dsp.exec_cmd([[emacsclient -c ~/notes/org/todo.org]]))


-- Monitor Config
hl.monitor({
    output   = "eDP-1",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- Cursor
hl.env("XCURSOR_THEME", "Adawaita")
hl.env("XCURSOR_SIZE", 20)

-- Screenshots
hl.bind("Print", hl.dsp.exec_cmd([[grim -g "$(slurp)" - | wl-copy]]))
hl.bind(mainMod .. " + " .. "F12", hl.dsp.exec_cmd("bash -c 'grim -g $(slurp) ~/Pictures/screenshot_$(date +%s).png'"))

-- Core Hyprland Configuration Block
hl.config({
     general = {
         gaps_in = 4,
         gaps_out = 4,
         gaps_workspaces = 0,
         border_size = 0,
         resize_on_border = false,
         allow_tearing = false,
         layout = "dwindle",
     },

     groups = {
         col = {
             active_border = { colors = { "rgba(d65d0eff)", "rgba(fe8019ee)" } },
         }
     },

     decoration = {
         rounding = 0,
         rounding_power = 0,
         active_opacity = 1.0,
         inactive_opacity = 1.0,

         shadow = {
             enabled = true,
             range = 10,
             render_power = 3,
             color = 0xee121212,
         },

         blur = {
             enabled = true,
             size = 7,
             passes = 1,
             vibrancy = 0.1696,
             ignore_opacity = true,
         },
     },

     misc = {
         force_default_wallpaper = -1,
         disable_hyprland_logo = false,
         vrr = 0,
     },
})

-- Animation Curves
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.curve("easy", { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

-- Animation Configs
hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Window Rules
hl.window_rule({
    name = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    no_focus = true,
})

hl.window_rule({ match = { title = "Picture-in-Picture" }, float = true, size = { 640, 360 } })
hl.window_rule({ match = { class = "chrome-calendar.google.com__-Default" }, float = true, size = { 1280, 720 } })

-- Layer Rules (Waybar, SwayNC, logout)
hl.layer_rule({ match = { namespace = "gtk-layer-shell" }, blur = true })
hl.layer_rule({ match = { namespace = "waybar" }, blur = false })
hl.layer_rule({ match = { namespace = "match:namespace notifications" }, blur = true })
hl.layer_rule({ match = { namespace = "match:namespace swaync-notification-window" }, blur = false })
hl.layer_rule({ match = { namespace = "match:namespace swaync-control-center" }, blur = false })
hl.layer_rule({ match = { namespace = "match:namespace logout_dialog" }, blur = true })

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("snappy-switcher --daemon")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("swaync")
    hl.exec_cmd("xsettingsd")
end)
